In [1]:
import numpy as np

In [27]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [31]:
a[0,1]=5
print(a)

[[1 5 3]
 [4 5 6]]


In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
b[0,1,1]

4

In [50]:
c= np.zeros((3,3))

In [52]:
np.full_like(c, 4)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
f = b.copy()
print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [61]:
np.matmul(f,b)

array([[[  7,  10],
        [ 15,  22]],

       [[ 67,  78],
        [ 91, 106]]])

In [63]:
np.linalg.det(f)

array([-2., -2.])

In [65]:
np.max(a)

6

In [67]:
aa = [1,2,3]
bb = [4,5,6]
cc = [7,8,9]
np.vstack([aa,bb,cc])
np.hstack([aa,bb,cc])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])